kind: pipeline
name: default

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    commands:
      - yarn lint:check

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      add_modules:
        - "@google/semantic-release-replace-plugin"
      mode: release
      update_readme_toc: true
      git_method: gh
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token

  - name: publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: docker.kilic.dev
      repo: docker.kilic.dev/${DRONE_REPO_NAME,,}
      entrypoint: "[ -f /drone/src/.tags ] && cat /drone/src/.tags && /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker || echo 'No need to publish new version.'"
      tags:
        - latest
      username:
        from_secret: docker_private_username
      password:
        from_secret: docker_private_password
