version: '3.7'
services:
  html-error-pages:
    image: docker.ev.kilic.dev/html-error-pages
    # ports:
    #   - 80:80
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
