version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/lerna-dev:latest
    environment:
      SERVICES: .
      PREFIX_LABEL: "false"
    ports:
      - 4200:4200
    volumes:
      - .:/data/app
